//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alishadev.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alishadev.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af-za
        ///am-et
        ///ar-ae
        ///ar-bh
        ///ar-dz
        ///ar-eg
        ///ar-iq
        ///ar-jo
        ///ar-kw
        ///ar-lb
        ///ar-ly
        ///ar-ma
        ///arn-cl
        ///ar-om
        ///ar-qa
        ///ar-sa
        ///ar-sd
        ///ar-sy
        ///ar-tn
        ///ar-ye
        ///as-in
        ///az-az
        ///az-cyrl-az
        ///az-latn-az
        ///ba-ru
        ///be-by
        ///bg-bg
        ///bn-bd
        ///bn-in
        ///bo-cn
        ///br-fr
        ///bs-cyrl-ba
        ///bs-latn-ba
        ///ca-es
        ///co-fr
        ///cs-cz
        ///cy-gb
        ///da-dk
        ///de-at
        ///de-ch
        ///de-de
        ///de-li
        ///de-lu
        ///dsb-de
        ///dv-mv
        ///el-cy
        ///el-gr
        ///en-001
        ///en-029
        ///en-au
        ///en-bz
        ///en-ca
        ///en-cb
        ///en-gb
        ///en-ie
        ///en-in
        ///en-jm
        ///en-mt
        ///en-my
        ///en-nz
        ///en-ph
        ///en-sg
        ///en-tt
        ///en-us
        ///en-za
        ///en-zw
        ///es-ar
        ///es-bo
        ///es-cl
        ///es-co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locales {
            get {
                return ResourceManager.GetString("locales", resourceCulture);
            }
        }
    }
}
